namespace Cirreum.Authorization.Configuration;

using Cirreum.AuthorizationProvider.Configuration;

public class ExternalAuthorizationSettings
	: AuthorizationProviderSettings<ExternalAuthorizationInstanceSettings>;